-- File Nest complete Supabase schema.
-- Run this in Supabase Dashboard -> SQL Editor.
-- It creates app metadata tables, RLS policies, a private Storage bucket,
-- and Storage policies that isolate each user's files by top-level path.

create extension if not exists pgcrypto;

-- App profile cache. Credentials stay in Supabase Auth.
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.folders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  emoji text not null default '📁',
  color text not null default '#e8855a',
  bg text not null default '#fde8de',
  pinned boolean not null default false,
  is_default boolean not null default false,
  note_body text not null default '',
  note_updated_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  folder_id bigint not null references public.folders(id) on delete cascade,
  original_name text not null,
  stored_name text not null unique, -- Supabase Storage object path: {user_id}/{timestamp}_{filename}
  extension text not null default '',
  file_size bigint not null default 0,
  ai_sorted boolean not null default false,
  keywords text not null default '',
  created_at timestamptz not null default now(),
  constraint files_stored_name_user_path check (stored_name like (user_id::text || '/%'))
);

-- One quick note per folder. The note is deleted with the folder row.
alter table public.folders add column if not exists note_body text not null default '';
alter table public.folders add column if not exists note_updated_at timestamptz;
update public.folders set note_body = '' where note_body is null;
alter table public.folders alter column note_body set default '';

create index if not exists idx_folders_user on public.folders(user_id);
create index if not exists idx_files_user on public.files(user_id);
create index if not exists idx_files_folder on public.files(folder_id);

-- Keep files.folder_id inside the same user boundary.
create or replace function public.folder_belongs_to_user(folder_id bigint, owner_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.folders
    where id = folder_id
      and user_id = owner_id
  );
$$;

alter table public.users enable row level security;
alter table public.folders enable row level security;
alter table public.files enable row level security;

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
on public.users for select
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.users;
create policy "Users can insert own profile"
on public.users for insert
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
on public.users for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can delete own profile" on public.users;
create policy "Users can delete own profile"
on public.users for delete
using (auth.uid() = id);

drop policy if exists "Users can read own folders" on public.folders;
create policy "Users can read own folders"
on public.folders for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own folders" on public.folders;
create policy "Users can insert own folders"
on public.folders for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own folders" on public.folders;
create policy "Users can update own folders"
on public.folders for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own folders" on public.folders;
create policy "Users can delete own folders"
on public.folders for delete
using (auth.uid() = user_id);

drop policy if exists "Users can read own files" on public.files;
create policy "Users can read own files"
on public.files for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own files" on public.files;
create policy "Users can insert own files"
on public.files for insert
with check (
  auth.uid() = user_id
  and public.folder_belongs_to_user(folder_id, user_id)
  and stored_name like (user_id::text || '/%')
);

drop policy if exists "Users can update own files" on public.files;
create policy "Users can update own files"
on public.files for update
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and public.folder_belongs_to_user(folder_id, user_id)
  and stored_name like (user_id::text || '/%')
);

drop policy if exists "Users can delete own files" on public.files;
create policy "Users can delete own files"
on public.files for delete
using (auth.uid() = user_id);

notify pgrst, 'reload schema';

-- Private Supabase Storage bucket for uploaded files.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('filenest-files', 'filenest-files', false, 52428800, null)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage object RLS: each object path must start with the authenticated user's UUID.
-- Example object name: {auth.uid()}/20260508123000000000_report.pdf
drop policy if exists "Users can read own storage objects" on storage.objects;
create policy "Users can read own storage objects"
on storage.objects for select
using (
  bucket_id = 'filenest-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can upload own storage objects" on storage.objects;
create policy "Users can upload own storage objects"
on storage.objects for insert
with check (
  bucket_id = 'filenest-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can update own storage objects" on storage.objects;
create policy "Users can update own storage objects"
on storage.objects for update
using (
  bucket_id = 'filenest-files'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'filenest-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can delete own storage objects" on storage.objects;
create policy "Users can delete own storage objects"
on storage.objects for delete
using (
  bucket_id = 'filenest-files'
  and (storage.foldername(name))[1] = auth.uid()::text
);
